name: Adventures in
description: ☼ Civic Engagement  ☼
meta_description: "thinkin bout stuff"
keywords: "life, justice, oppression, freedom"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: https://gaargly.github.io/
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate, jekyll-seo-tag]


# Details for the RSS feed generator
url:            'https://gaargly.github.io/'
author:         'gaargly'
